spring.application.name=Portal

# Connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/JobPortal
spring.datasource.username=root
spring.datasource.password=hiya15

# Hibernate settings (Updates schema automatically and logs queries)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-location=classpath:data.sql

logging.level.org.springframework.security=DEBUG